
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment-v2
  labels:
    app: my-k8s-deploy
    env: prod
    owner: th1nksnow

spec:
  replicas: 3
  selector:
    matchLabels:
      project: v2
  template:
    metadata:
      labels:
        project: v2
    spec:
      containers:
        - name: php-container
          image: th1nksnow/k8sphp:latest
          ports:
            - containerPort: 80

...
